filetype on
syntax on

set number
set cursorline
set cursorcolumn
set colorcolumn=80
 
highlight LineNr ctermfg=darkgrey
highlight colorcolumn ctermbg=236
highlight cursorline cterm=NONE ctermbg=236
highlight cursorcolumn ctermbg=236

set hidden
set history=100

set nowrap
set tabstop=4
set shiftwidth=4
set noexpandtab
set smartindent

set hlsearch
set showmatch
