filetype on
syntax on

set number
set cursorline
set cursorcolumn
set colorcolumn=80
 
highlight LineNr ctermfg=15
highlight colorcolumn ctermbg=0
highlight cursorline cterm=NONE ctermbg=0
highlight cursorcolumn ctermbg=0

set hidden
set history=100

set nowrap
set tabstop=4
set shiftwidth=4
set noexpandtab
set smartindent

set hlsearch
set showmatch
